function checkWeather(run) {
 const stamp = s => Date.parse(s) / 1000;
 const base = stamp('2026-09-14T00:00:00Z');
 function fixture() {
  const time = Array.from({length:73}, (_,i)=>base+i*3600);
  return {timezone:'Europe/Zurich',daily:{
   sunrise:[stamp('2026-09-14T05:12:00Z'),stamp('2026-09-15T05:13:00Z')],
   sunset:[stamp('2026-09-14T17:38:00Z'),stamp('2026-09-15T17:36:00Z')]},
   hourly:{time,temperature_2m:time.map(()=>20),precipitation_probability:time.map(()=>0),precipitation:time.map(()=>0),wind_speed_10m:time.map(()=>6),weather_code:time.map(()=>0)}};
 }
 const passed=[]; const test=(name,fn)=>{if(!fn())throw new Error(name);passed.push(name);};
 let data=fixture(), now=stamp('2026-09-14T14:08:00Z'), r=run(data,now);
 test('daylight defaults to current daytime window',()=>r.window==='Now–19:00');
 test('duration uses remaining current hour',()=>r.duration==='2h 52m');
 test('today is explicit',()=>r.date.startsWith('Today'));
 now=stamp('2026-09-14T20:08:00Z'); r=run(data,now);
 test('evening finds tomorrow beyond twelve hours',()=>r.window==='08:00–19:00'&&r.date.startsWith('Tomorrow'));
 test('timeline follows recommended day',()=>r.hours[0].day==='Tomorrow'&&r.hours[0].time==='08:00');
 test('sunrise is rounded inward to forecast boundary',()=>r.hours[0].start>=data.daily.sunrise[1]);
 data=fixture();delete data.daily;
 test('missing sunrise is explicit',()=>run(data,now).headline==='Daylight unavailable');
 data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any'}}};
 r=run(data,now);
 test('any time works without sunrise',()=>r.found&&r.window.startsWith('Now'));
 test('search stops at end of tomorrow',()=>r.window.endsWith('00:00'));
 data=fixture();data.hourly.precipitation_probability.fill(null);
 test('missing rain data is explicit',()=>run(data,now).headline==='Forecast incomplete');
 data=fixture();data.hourly.weather_code.fill(95);
 test('storms cannot become outdoor windows',()=>!run(data,now).found);
 test('empty forecast is unavailable',()=>run({},now).headline==='Forecast unavailable');
 test('invalid injected clock falls back without throwing',()=>run({},NaN).headline==='Forecast unavailable');
 data=fixture();data.daily.sunrise=[null,null];data.daily.sunset=[null,null];
 test('polar/missing solar times do not imply daylight',()=>run(data,now).headline==='Daylight unavailable');
 data=fixture();now=stamp('2026-09-14T16:30:00Z');
 data.trmnl={plugin_settings:{custom_fields_values:{minimum_hours:'1'}}};
 test('short remaining daylight shifts to tomorrow',()=>run(data,now).date.startsWith('Tomorrow'));
 data=fixture(); now=stamp('2026-09-14T14:08:00Z'); data.hourly.precipitation_probability[16]=90;
 test('rain in preceding interval ends window',()=>run(data,now).window==='Now–17:00' || !run(data,now).window.startsWith('Now'));
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{units:'imperial'}}};
 test('imperial units retained',()=>run(data,now).temperature.includes('68°F')&&run(data,now).wind.includes('mph'));
 data=fixture();data.hourly.precipitation.fill(2);
 test('rain amount excludes otherwise low probability',()=>!run(data,now).found);
 data=fixture();now=stamp('2026-09-14T20:08:00Z');r=run(data,now);
 test('ribbon selection has positive width',()=>r.ribbon.selection.width>0);
 const first=data.hourly.time.find(t=>t+3600>now);
 const final=stamp('2026-09-15T22:00:00Z');
 const expected=40+880*(stamp('2026-09-15T06:00:00Z')-first)/(final-first);
 test('ribbon selection aligns with actual start timestamp',()=>Math.abs(r.ribbon.selection.x-expected)<0.02);
 test('night shading exists for overnight outlook',()=>r.ribbon.nights.length>0);
 data=fixture();data.hourly.temperature_2m[22]=null;
 r=run(data,now);
 test('missing temperatures break line',()=>r.ribbon.path.split('M').length>=3);
 data=fixture();data.hourly.precipitation_probability[23]=null;
 test('missing rain remains unknown',()=>run(data,now).ribbon.bars.some(b=>b.unknown));
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',rain_limit:'broken'}}};
 data.hourly.precipitation_probability.fill(10);r=run(data,stamp('2026-09-14T14:08:00Z'));
 test('invalid rain limit uses documented default',()=>r.threshold===20&&r.found);
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',minimum_hours:'2'}}};
 now=stamp('2026-09-14T14:00:00Z');Object.keys(data.hourly).forEach(k=>data.hourly[k]=data.hourly[k].slice(0,17));r=run(data,now);
 test('exact minimum duration qualifies',()=>r.found&&r.duration==='2h');
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',minimum_hours:'2'}}};
 now=stamp('2026-09-14T14:08:00Z');Object.keys(data.hourly).forEach(k=>data.hourly[k]=data.hourly[k].slice(0,16));r=run(data,now);
 test('truncated forecast is distinguished',()=>r.headline==='Not enough forecast data');
 data=fixture();now=stamp('2026-09-18T00:00:00Z');
 test('stale forecast is explicit',()=>run(data,now).headline==='Forecast outdated');
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',minimum_hours:'2'}}};now=stamp('2026-09-14T14:08:00Z');data.hourly.time[16]=data.hourly.time[15];
 test('duplicate timestamp does not bridge a window',()=>!run(data,now).window.startsWith('Now'));
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',minimum_hours:'2'}}};data.hourly.time[16]=data.hourly.time[14];
 test('out-of-order timestamp does not bridge a window',()=>!run(data,now).window.startsWith('Now'));
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any'}}};data.hourly.time.splice(15,1);
 test('gap at current time is reported incomplete',()=>run(data,now).headline==='Forecast incomplete');
 const shiftedFixture=(iso,zone)=>{const d=fixture(),delta=stamp(iso)-base;d.timezone=zone;d.hourly.time=d.hourly.time.map(t=>t+delta);d.daily.sunrise=d.daily.sunrise.map(t=>t+delta);d.daily.sunset=d.daily.sunset.map(t=>t+delta);d.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any'}}};return d;};
 data=shiftedFixture('2026-12-31T00:00:00Z','Europe/Zurich');now=stamp('2026-12-31T20:08:00Z');r=run(data,now);
 test('year rollover keeps tomorrow searchable',()=>r.found&&r.hours.some(h=>h.day==='Tomorrow'));
 data=shiftedFixture('2026-10-25T00:00:00Z','Europe/Zurich');now=stamp('2026-10-25T00:30:00Z');
 test('DST transition remains usable',()=>run(data,now).found);
 data=shiftedFixture('2026-09-14T00:00:00Z','Asia/Kathmandu');now=stamp('2026-09-14T14:08:00Z');
 test('non-whole-hour timezone remains usable',()=>run(data,now).found);
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any',units:'imperial'}}};data.hourly.temperature_2m.fill(-20);
 test('negative imperial temperature converts correctly',()=>run(data,stamp('2026-09-14T14:08:00Z')).temperature.includes('-4°F'));
 data=fixture();data.trmnl={plugin_settings:{custom_fields_values:{daylight_mode:'any'}}};data.hourly.temperature_2m.fill(null);data.hourly.wind_speed_10m.fill(null);r=run(data,stamp('2026-09-14T14:08:00Z'));
 test('missing supporting values stay explicit',()=>r.found&&r.temperature==='Temperature unavailable'&&r.wind==='Wind unavailable');
 data=fixture();now=stamp('2026-09-14T14:08:00Z');r=run(data,now);
 test('successful refresh has explicit state',()=>r.state==='ok'&&r.checkedAt===now);
 test('model issue time is not invented',()=>r.modelIssuedAt===null&&r.updated.startsWith('Checked '));
 r=run({error:'upstream timeout'},now);
 test('polling error is explicit and rejects cached implication',()=>r.state==='service_error'&&r.headline==='Weather service unavailable'&&r.detail.includes('no cached forecast'));
 r=run(fixture(),now);
 test('valid data recovers after an error',()=>r.state==='ok'&&r.found);
 data=fixture();r=run(data,stamp('2026-09-18T00:00:00Z'));
 test('outdated state does not claim current data',()=>r.state==='outdated'&&r.detail.includes('not shown as current'));
 test('empty input has unavailable state',()=>run({},now).state==='unavailable');
 return passed;
}
if(typeof module!=='undefined')module.exports={checkWeather};
